export const attendanceData = [
  { name: 0, Present: 0, Absent: 0, Off: 0, Holidays: 0 },
  { name: 1, Present: 3, Absent: 0, Off: 0, Holidays: 0 },
  { name: 2, Present: 16, Absent: 0, Off: 0, Holidays: 0 },
  { name: 3, Present: 10, Absent: 0, Off: 0, Holidays: 0 },
  { name: 4, Present: 14, Absent: 0, Off: 0, Holidays: 0 },
  { name: 5, Present: 12, Absent: 0, Off: 0, Holidays: 0 },
  { name: 6, Present: 0, Absent: 0, Off: 13, Holidays: 0 },
  { name: 7, Present: 0, Absent: 0, Off: 7, Holidays: 0 },
  { name: 8, Present: 2, Absent: 0, Off: 0, Holidays: 0 },
  { name: 9, Present: 0, Absent: 0, Off: 0, Holidays: 17 },
  { name: 10, Present: 4, Absent: 0, Off: 0, Holidays: 0 },
  { name: 11, Present: 0, Absent: 10, Off: 0, Holidays: 0 },
  { name: 12, Present: 10, Absent: 0, Off: 0, Holidays: 0 },
  { name: 13, Present: 4, Absent: 0, Off: 0, Holidays: 0 },
  { name: 14, Present: 0, Absent: 0, Off: 0, Holidays: 0 },
  { name: 15, Present: 1, Absent: 0, Off: 0, Holidays: 0 },
  { name: 16, Present: 13, Absent: 0, Off: 0, Holidays: 0 },
  { name: 17, Present: 0, Absent: 0, Off: 0, Holidays: 17 },
  { name: 18, Present: 6, Absent: 0, Off: 0, Holidays: 0 },
  { name: 19, Present: 13, Absent: 0, Off: 0, Holidays: 0 },
  { name: 20, Present: 0, Absent: 0, Off: 0, Holidays: 0 },
  { name: 21, Present: 12, Absent: 0, Off: 0, Holidays: 0 },
  { name: 22, Present: 0, Absent: 11, Off: 0, Holidays: 0 },
  { name: 23, Present: 0, Absent: 0, Off: 0, Holidays: 15 },
  { name: 24, Present: 18, Absent: 0, Off: 0, Holidays: 0 },
  { name: 25, Present: 0, Absent: 16, Off: 0, Holidays: 0 },
  { name: 26, Present: 12, Absent: 0, Off: 0, Holidays: 0 },
  { name: 27, Present: 9, Absent: 0, Off: 0, Holidays: 0 },
  { name: 28, Present: 14, Absent: 0, Off: 0, Holidays: 0 },
  { name: 29, Present: 0, Absent: 0, Off: 0, Holidays: 20 },
];

 export const Leavesummery = [
    { name: "Leave Taken", value: 10 },
    { name: "Total Leave", value: 30 },
    { name: "Leave Balence", value: 5 },
    { name: "Sick Leave", value: 5 },
  ]